//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleanex_pert3
{
    using System;
    using System.Collections.Generic;
    
    public partial class External_Missions
    {
        public int ExtEventID { get; set; }
        public string ExtTitle { get; set; }
        public string ExtDescription { get; set; }
        public string ExtTools { get; set; }
        public string ExtLocation { get; set; }
        public string ExtAddress { get; set; }
        public Nullable<int> ExtKeyNr { get; set; }
        public string ExtFieldOfWork { get; set; }
        public Nullable<System.DateTime> ExtWeek { get; set; }
    }
}
