//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleanex_pert3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Missions
    {
        public int MissionID { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string ParkingZone { get; set; }
        public string FieldOfWork { get; set; }
        public string Tools { get; set; }
        public string JobDescription { get; set; }
        public string KeyNr { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Partner { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
    }
}
